---
# roles/deploy/tasks/main.yml

- name: Install git
  apt:
    pkg: git
    state: present
  sudo: yes

- name: Create www directory
  file:
    path: /srv/www
    owner: ubuntu
    group: ubuntu
    state: directory
  sudo: yes

- name: Clone repository
  git:
    repo: "https://github.com/atplanet/hello-world-express-app.git"
    dest: /srv/www/webapp
    version: master

- name: Install upstart script
  copy:
    src: upstart.conf
    dest: /etc/upstart/webapp.conf
  sudo: yes

- name: Enable and start the application
  service:
    name: webapp
    enabled: yes
    state: restarted
  sudo: yes
